In [1]:
# ---------------------------------------------------------------
# python importa la libreria OS che controlla il sistema operativo
import os 
# ---------------------------------------------------------------
# python importa la libreria Pandas che permette l'importazione ed analisi dei dati: potrà essere richiamata come PD
import pandas as pd 

#importo le librerie di visualizzazione dei grafici
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

#importa la libreria per la pulitura del dataset
from corso_lib import restituisci_dataset

In [2]:
'''
Tavola 3.1 segue - Persone di 30-34 anni che hanno conseguito 
un titolo universitario per sesso, regione e ripartizione geografica - Anni 2004-2015 (valori percentuali)
'''

totale_istruzione = restituisci_dataset(
    posizione_del_dataset = os.path.join(os.getcwd(), "Appendice-statistica-2016", "02.Istruzione", "Cap_02_Istruzione 03.xlsx"),
    nome_del_foglio = "REG totale", #inserire il nome del foglio
    riga_intestazione_colonna = 4, # inserire la riga in cui è presente l'intestazione di colonna 
    riga_sottotabella= None, # None - da divisione fra le due tabelle "maschi - femmine" dovrebbe cadere intorno alla riga 36
    tabella = None # None - qui si può mettere "maschi" - "femmine"
)
totale_istruzione.head()

4,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0
REGIONI E RIPARTIZIONI GEOGRAFICHE,,,,,,,,,,,,
Piemonte,15.414345,16.633689,18.022680,19.846680,17.956827,17.825633,20.141706,20.524346,22.178592,23.338717,24.180373,23.960124
Valle d'Aosta/Vallée d'Aoste,12.958604,16.019083,16.028654,17.975581,18.976916,14.907002,15.841965,18.009456,19.031090,18.800211,20.700017,25.919679
Liguria,17.952786,16.511959,21.517549,21.063116,22.042858,23.781642,24.716662,23.682985,27.847217,27.520420,31.321860,26.200943
Lombardia,16.944853,18.683977,19.468957,19.910380,20.886743,21.563470,22.833135,22.252287,23.430828,25.713336,25.858176,29.461258
Trentino-Alto Adige/Südtirol,13.622331,15.043845,16.757742,17.277207,17.923088,17.987725,22.070451,25.244287,24.518632,23.781042,24.973215,28.429509

In [4]:
maschi = restituisci_dataset(
    posizione_del_dataset = os.path.join(os.getcwd(), "Appendice-statistica-2016", "02.Istruzione", "Cap_02_Istruzione 03.xlsx"),
    nome_del_foglio = "REG Maschi-Femmine",
    riga_intestazione_colonna = 4,
    riga_sottotabella=36, # None - da divisione fra le due tabelle "maschi - femmine" dovrebbe cadere intorno alla riga 36
    tabella = "maschi" # None - qui si può mettere "maschi" - "femmine"
)

In [5]:
femmine = restituisci_dataset(
    posizione_del_dataset = os.path.join(os.getcwd(), "Appendice-statistica-2016", "02.Istruzione", "Cap_02_Istruzione 03.xlsx"),
    nome_del_foglio = "REG Maschi-Femmine",
    riga_intestazione_colonna = 4,
    riga_sottotabella=36, # None - da divisione fra le due tabelle "maschi - femmine" dovrebbe cadere intorno alla riga 36
    tabella = "femmine" # None - qui si può mettere "maschi" - "femmine"
)

In [6]:
(maschi / femmine).head()

4,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0
REGIONI E RIPARTIZIONI GEOGRAFICHE,,,,,,,,,,,,
Piemonte,0.657221,0.715366,0.778831,0.724219,0.666949,0.780996,0.676815,0.616393,0.587839,0.589900,0.698831,0.624049
Valle d'Aosta/Vallée d'Aoste,0.465812,0.635658,0.654504,0.624844,0.625900,0.495959,0.494506,0.549811,0.721448,0.624103,0.424110,0.576656
Liguria,0.723850,0.940652,0.679440,0.566401,0.620442,0.781700,0.789012,0.714890,0.636994,0.602129,0.556442,0.491996
Lombardia,0.779679,0.676383,0.680282,0.625006,0.548415,0.687153,0.673862,0.666182,0.683059,0.687965,0.699290,0.739627
Trentino-Alto Adige/Südtirol,0.749369,0.753806,0.580720,0.790837,0.734808,0.695397,0.816678,0.704169,0.645878,0.506593,0.574917,0.523950

In [7]:
restituisci_dataset(
    posizione_del_dataset = os.path.join(os.getcwd(), "Appendice-statistica-2016", "02.Istruzione", "Cap_02_Istruzione 03.xlsx"),
    nome_del_foglio = "SESSO e ETA",
    riga_intestazione_colonna = 3,
    riga_sottotabella= None, # None - da divisione fra le due tabelle "maschi - femmine" dovrebbe cadere intorno alla riga 36
    tabella = None # None - qui si può mettere "maschi" - "femmine"
)

3,2004.0,2005.0,2006.0,2007.0,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0
SESSO,,,,,,,,,,,,
Maschi,12.802629,14.083731,14.187762,14.976646,14.890812,14.971085,15.579645,15.881305,17.261841,17.745024,18.765741,19.959366
Femmine,18.423501,20.056075,21.148387,22.199333,23.514525,22.965891,24.180319,24.829701,26.473425,27.308421,29.056805,30.758605
Totale,15.601584,17.052269,17.648708,18.572547,19.192637,18.966831,19.889490,20.372845,21.885562,22.535986,23.911894,25.347701